// Generated by CoffeeScript 1.9.3

/*
  Wadi sms tool web interface
 */

(function() {
  angular.module('Wadi', ['ui.router', 'ui.select', 'ui.bootstrap', 'ngSanitize', 'isteven-multi-select', 'Wadi.controllers.form', 'Wadi.controllers.main', 'Wadi.directives', 'Wadi.constants']).config(function($stateProvider, $urlRouterProvider, uiSelectConfig) {
    uiSelectConfig.theme = 'bootstrap';
    return $stateProvider.state('login', {
      templateUrl: './templates/view_login.html',
      controller: 'LoginCtrl'
    }).state('form', {
      templateUrl: './templates/view_main.html',
      controller: 'FormCtrl',
      url: '/form'
    }).state('dashboard', {
      templateUrl: './templates/view_dashboard.html',
      url: '/dashboard'
    }).state('block_list', {
      templateUrl: './templates/view_block_list.html',
      url: './block_list'
    }).state('test', {
      templateUrl: './templates/view_test.html',
      controller: 'TestCtrl',
      url: '/test'
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
