// Generated by CoffeeScript 1.9.3

/*
  Wadi sms tool web interface
 */

(function() {
  angular.module('Wadi', ['ui.router', 'ui.select', 'ui.bootstrap', 'ngSanitize', 'Wadi.controllers.form', 'Wadi.controllers.main', 'Wadi.directives', 'Wadi.constants']).config(function($stateProvider, $urlRouterProvider, uiSelectConfig) {
    uiSelectConfig.theme = 'bootstrap';
    return $stateProvider.state('login', {
      templateUrl: './templates/view_login.html',
      controller: 'LoginCtrl'
    }).state('form', {
      templateUrl: './templates/view_main.html',
      controller: 'FormCtrl'
    }).state('test', {
      templateUrl: './templates/view_test.html',
      controller: 'TestCtrl'
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
