// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('Wadi.form', []).controller('FormCtrl', function($scope, $state, $log, $http) {
    var configureForm, formPartial;
    $scope.checkLogin = function() {
      $log.info("Checking login status at FormCtrl");
      if (!$scope.$parent.checkLogin()) {
        return $state.go('login');
      }
    };
    $http.get('http://45.55.72.208/wadi/interface/form').success(function(data) {
      return configureForm(data);
    });
    $scope.simpleParts = [];
    $scope.selectedSimpleParts = {};
    $scope.advancedParts = {};
    $scope.selectedAdvancedParts = {};
    configureForm = function(data) {
      var i, j, k, len, len1, ref, ref1, results, tranformValues;
      tranformValues = function(d) {
        var v;
        v = d.values;
        return d.values = _.map(v, function(op) {
          return {
            id: op,
            label: op
          };
        });
      };
      $scope.simpleParts = [];
      $scope.advancedParts = {};
      $scope.campaign = {
        text: {
          arabic: '',
          english: ''
        },
        date: '',
        time: ''
      };
      ref = ['category'];
      for (i = 0, len = ref.length; i < len; i++) {
        k = ref[i];
        $scope.selectedSimpleParts[k] = [];
        tranformValues(data[k]);
        $scope.simpleParts.push(data[k]);
      }
      $log.info("Configured simple: " + JSON.stringify($scope.simpleParts));
      ref1 = ['customer'];
      results = [];
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        k = ref1[j];
        tranformValues(data[k]);
        $scope.selectedAdvancedParts[k] = [];
        results.push($scope.advancedParts[k] = data[k]);
      }
      return results;
    };
    formPartial = function() {
      var k, ref, result, reverseTransform, temp, v;
      reverseTransform = function(v) {
        return _.map(v, function(o) {
          return o.id;
        });
      };
      result = {};
      ref = $scope.selectedSimpleParts;
      for (k in ref) {
        v = ref[k];
        v = reverseTransform(v);
        result[k] = v;
      }
      temp = $scope.selectedAdvancedParts['customer'];
      if (temp.length === 2 || temp.length === 0) {
        result['mode'] = 'all';
      } else {
        result['mode'] = temp[0].id;
      }
      $log.debug("Form submission: " + (JSON.stringify(result)));
      return result;
    };
    return $scope.submit = function() {
      var result;
      result = {};
      result['target_config'] = formPartial();
      result['campaign'] = $scope.campaign;
      $log.info("Posting: " + JSON.stringify(result));
      return $http.post('http://45.55.72.208/wadi/interface/post', result).success(function(res) {
        return $log.info("Got result: " + JSON.stringify(res));
      });
    };
  });

}).call(this);

//# sourceMappingURL=app_form.js.map
