// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('Wadi.constants', []).constant('wdLinks', {
    scheduling_sheet: "https://docs.google.com/spreadsheets/d/144fuYSOgi8md4n2Ezoj9yNMi6AigoXrkHA9rWIF0EDw/edit",
    docs: "http://45.55.72.208/interface/wadi/docs.html"
  });

}).call(this);

//# sourceMappingURL=constants.js.map
