// Generated by CoffeeScript 1.9.3

/*
  Works like a charm :D
  Tested on Sat, 15 Aug, 06:44 PM
 */

(function() {
  angular.module('Wadi.directives', []).directive('wdRangeInput', function() {
    return {
      restrict: 'E',
      scope: {
        label: '=label',
        model: '=model'
      },
      templateUrl: './templates/dir_range.html',
      controller: function($scope, $log) {
        var compileResult;
        $scope.lt = "Less than";
        $scope.eq = "Equal to";
        $scope.gt = "More than";
        $scope.bw = "Between";
        $scope.data = {
          op: '',
          min: 1,
          max: 2
        };
        compileResult = function() {
          return $scope.model = (function() {
            switch ($scope.data.op) {
              case '':
                return '';
              case $scope.bw:
                return $scope.bw + " " + $scope.data.min + " and " + $scope.data.max;
              case $scope.eq:
                return "" + $scope.data.min;
              default:
                return $scope.data.op + " " + $scope.data.min;
            }
          })();
        };
        $scope.$watchCollection('data', function(nVal, oVal) {
          if (nVal.min !== oVal.min && nVal.min !== null && nVal.min >= nVal.max) {
            $scope.data.max = $scope.data.min + 1;
          }
          if (nVal.max !== oVal.max && nVal.max !== null && nVal.max <= nVal.min) {
            $scope.data.min = $scope.data.max - 1;
          }
          return compileResult();
        });
        $scope.$watch('model', function(nVal, oVal) {
          if (oVal !== '' && nVal === '') {
            return $scope.data.op = '';
          }
        });
        return $scope.recover = function() {
          if ($scope.data.min === null || $scope.data.min <= 0) {
            $scope.data.min = 1;
          }
          if ($scope.data.max === null) {
            return $scope.data.max = $scope.data.min + 1;
          }
        };
      }
    };
  });

}).call(this);

//# sourceMappingURL=directives.js.map
