// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('Wadi.services', []).factory('testFn', function($log) {
    return function() {
      return $log.debug("Test function executed");
    };
  }).factory('wdConfirm', function($modal) {
    return function(title, message, sz) {
      var size;
      if (sz) {
        size = sz;
      } else {
        size = 'sm';
      }
      return $modal.open({
        templateUrl: 'templates/modals/modal_confirm.html',
        size: size,
        controller: function($scope) {
          $scope.message = message;
          return $scope.title = title;
        }
      });
    };
  });

}).call(this);

//# sourceMappingURL=services.js.map
