// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('Wadi.services', []).factory('testFn', function($log) {
    return function() {
      return $log.debug("Test function executed");
    };
  }).factory('wdConfirm', function($modal) {
    return function(title, message, sz) {
      var size;
      if (sz) {
        size = sz;
      } else {
        size = 'sm';
      }
      return $modal.open({
        templateUrl: 'templates/modals/modal_confirm.html',
        size: size,
        controller: function($scope) {
          $scope.message = message;
          return $scope.title = title;
        }
      }).result;
    };
  }).factory('wdToast', function() {
    if (!window.toastr) {
      return function(title, message) {
        return alert(title + ":  " + message);
      };
    } else {
      toastr.options = {
        closeButton: true,
        debug: false,
        positionClass: "toast-bottom-full-width",
        preventDuplicate: true,
        onclick: null,
        showDuration: 300,
        hideDuration: 1000,
        timeout: 4000,
        extendedTimeOut: 0,
        showEasing: "swing",
        hideEasing: "linear",
        showMethod: "fadeIn",
        hideMethod: "fadeOut"
      };
      return function(title, message, style) {
        if (style == null) {
          style = "success";
        }
        toastr[style](message, title);
        return true;
      };
    }
  }).factory('wdSegment', function($modal) {
    return function(job, debug) {
      return $modal.open({
        templateUrl: 'templates/modals/modal_segment_job.html',
        backdrop: 'static',
        size: 'lg',
        keyboard: false,
        resolve: {
          job: function() {
            return job;
          },
          debug: function() {
            if (debug) {
              return debug;
            } else {
              return false;
            }
          }
        },
        controller: 'wdSegmentCtrl'
      }).result;
    };
  }).factory('wdExternalSegment', function($modal) {
    var basicOptions;
    basicOptions = {
      templateUrl: 'templates/modals/modal_external_segment.html',
      backdrop: 'static',
      size: 'lg',
      keyboard: false,
      controller: 'wdExternalSegmentCtrl'
    };
    return {
      new_segments: function(count) {
        basicOptions.resolve = {
          options: function() {
            return {
              showDetails: true,
              is_new: true,
              total: count
            };
          },
          segments: function() {
            return [];
          }
        };
        return $modal.open(basicOptions).result;
      },
      old_segment: function(seg_num) {
        basicOptions.resolve = {
          options: function() {
            return {
              showDetails: false,
              is_new: false
            };
          },
          segments: function() {
            return [seg_num];
          }
        };
        return $modal.open(basicOptions).result;
      }
    };
  });

}).call(this);

//# sourceMappingURL=services.js.map
