// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('Wadi.services', []).factory('testFn', function($log) {
    return function() {
      return $log.debug("Test function executed");
    };
  }).factory('wdConfirm', function($modal) {
    return function(message) {
      return $modal.open({
        templateUrl: 'templates/modals/modal_confirm.html',
        controller: function($scope, $modalInstance) {
          $scope.message = message;
          $scope.cancel = function() {
            return $modalInstance.dismiss('cancel');
          };
          return $scope.ok = function() {
            return $modalInstance.ok('ok');
          };
        }
      });
    };
  });

}).call(this);

//# sourceMappingURL=services.js.map
