// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('Wadi.controllers.external', []).controller('ExternalDataCtrl', function($scope, wdInterfaceApi, $interval, $http) {
    var periodicRefresh, refresh;
    $scope.data = [];
    $scope.unsegmented_count = 0;
    refresh = function() {
      return $http.get(wdInterfaceApi.segment_jobs_external).success(function(data) {
        if (data.success) {
          $scope.data = data.data;
          return $scope.unsegmented_count = data.unsegmented;
        } else {
          return $log.debug("Didn't get correct data for external jobs");
        }
      });
    };
    refresh();
    periodicRefresh = $interval(function() {
      return refresh();
    }, 10000);
    return $scope.$on("$destroy", function() {
      return $interval.cancel(periodicRefresh);
    });
  });

}).call(this);

//# sourceMappingURL=external.js.map
