// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('Wadi.controllers.main', []).controller('MainCtrl', function($scope, $state, $http, $log, wdLinks) {
    var isLoggedIn;
    $log.debug("Main executed");
    $state.go('login');
    isLoggedIn = false;
    $scope.checkLogin = function() {
      return isLoggedIn;
    };
    $scope.sheet_link = wdLinks.scheduling_sheet;
    $scope.doc_link = wdLinks.docs;
    $scope.login = function(username, pass) {
      $log.debug("Got submission " + username + ", " + pass);
      return $http.post("http://45.55.72.208/wadi/interface/login", {
        username: username,
        password: pass
      }).success(function(result) {
        $log.debug("Got result: " + (JSON.stringify(result)));
        isLoggedIn = result.success;
        if (isLoggedIn) {
          return $state.go('form');
        } else {
          return alert("Authentication failed");
        }
      });
    };
    $scope.isState = function(statename) {
      return $state.is(statename);
    };
    return $scope.goTo = function(statename) {
      return $state.go(statename);
    };
  }).controller('LoginCtrl', function($scope, $log) {
    $scope.data = {
      username: '',
      password: ''
    };
    return $scope.submit = function() {
      $log.debug("Submitting : " + (JSON.stringify($scope.data)));
      $scope.$parent.login($scope.data.username, md5($scope.data.password));
      $scope.data.username = '';
      return $scope.data.password = '';
    };
  }).controller('TestCtrl', function($scope, $state, $log, wdLinks, $modal, Upload) {
    $scope.submit = function() {
      if ($scope.file && !$scope.file.$error) {
        return $scope.upload($scope.file);
      }
    };
    return $scope.upload = function(file) {
      return Upload.upload({
        url: 'http://45.55.72.208/wadi/block_list/upload',
        file: file
      }).progress(function(evt) {
        var progPerc;
        progPerc = parseInt(100.0 * evt.loaded / evt.total);
        return $log.info("Progress: " + progPerc + "% " + evt.config.file.name);
      }).success(function(data) {
        return $log.info("Got result: " + JSON.stringify(data));
      });
    };
  });

}).call(this);

//# sourceMappingURL=main.js.map
