// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('Wadi.controllers.main', []).controller('MainCtrl', function($scope, $state, $http, $log, wdLinks) {
    var isLoggedIn;
    $log.debug("Main executed");
    $state.go('login');
    isLoggedIn = false;
    $scope.checkLogin = function() {
      return isLoggedIn;
    };
    $scope.sheet_link = wdLinks.scheduling_sheet;
    $scope.doc_link = wdLinks.docs;
    return $scope.login = function(username, pass) {
      $log.debug("Got submission " + username + ", " + pass);
      return $http.post("http://45.55.72.208/wadi/interface/login", {
        username: username,
        password: pass
      }).success(function(result) {
        $log.debug("Got result: " + (JSON.stringify(result)));
        isLoggedIn = result.success;
        if (isLoggedIn) {
          return $state.go('form');
        } else {
          return alert("Authentication failed");
        }
      });
    };
  }).controller('LoginCtrl', function($scope, $log) {
    $scope.data = {
      username: '',
      password: ''
    };
    return $scope.submit = function() {
      $log.debug("Submitting : " + (JSON.stringify($scope.data)));
      $scope.$parent.login($scope.data.username, md5($scope.data.password));
      $scope.data.username = '';
      return $scope.data.password = '';
    };
  }).controller('TestCtrl', function($scope, $state, $log) {
    $scope.data = {
      selected: [],
      set: ''
    };
    return $scope.sampleData = ['electronics', 'shoes', 'sports bags', 'goodies', 'long list', 'another useless item', 'someone else'];
  });

}).call(this);

//# sourceMappingURL=main.js.map
